### ISSUE TITLE
Second digital signature invalidates the first one

### ISSUE THREAD

**Issue by ugochirico** [podofo/podofo#4] opened 2022-08-12 12:58 UTC
When you apply a second digital signature to a pdf that already has a digital signature, the first one is invalidated, this digital signature is not more valid and adobe reader says "the document has been modified after the digital signature".

This happens because the incremental update doesn't work correctly.

**Comment by ceztko** [comment] 2022-08-17 10:01
The incremental update mechanism is a complex beast and there are many bugs in legacy PoDoDo. In my tests, the main reason the previous signatures invalidates after the following one is that the incremental update unnecessarily rewrites several objects of the previous revision. The objects may be rewritten without changes but Acrobat Reader decides this is a violation of the restrictions that are imposed in incremental updates to consider previous signatures as valid. With this regard, PoDoFo was buggy/lacking in these areas:
- Handling of XRef entries for in use/free objects during incremental updates;
- Correct tracking of dirty flags in objects after document load or when manipulating it;
- Support of XRef streams in incremental updates.

All of these areas were taken care in pdfmm in several commits through the last 2-3 years. Here it follows an incomplete list:

- PdfXRef: Fixed handling XRefStm documents https://github.com/pdfmm/pdfmm/commit/556ce762a3a816685184364c777bb4b4cb4a3073
- Cleaning PdfXRef, PdfWriter, PdfXRefStream https://github.com/pdfmm/pdfmm/commit/9cbbc00e481c0eb3bb86758f141fc52cf536feed
- PdfStreamObject: Fix wrongly marking objects dirty on stream creation during parsing https://github.com/pdfmm/pdfmm/commit/aa66de2c4107532cd7b9513984fbd4ea7f807465
- PdfObject: Improving SetDirty/ResetDirty handling https://github.com/pdfmm/pdfmm/commit/9f23c37733af6cd25c4f479ef7de605403592fae
- PdfXRefStream: Fix writing offset of XRefStm object in its entries data https://github.com/pdfmm/pdfmm/commit/94899d8036d0b909ed50902bbf8c5c68264adb6f
- PdfObjectStreamParserObject: Stop removing objects after parsing https://github.com/pdfmm/pdfmm/commit/1712a01bb7b94bd9fd881816bfac4fb9948664ca

This probably means that there's no simple fix for the kind of issue you're seeing, not at least in the general case. One option would be (keep trying?) using pdfmm, or wait for PoDoFo-next to be introduced, which should be a matter of weeks[1], and trying to see if this fixes the issue for you. Other options is looking through the list of commits I wrote here to look if you can craft a fix yourself, or find other maintainers interested in looking through this issue in 0.9.x. As I previously clarified with the community, I won't look through 0.9.x code.

[1] https://www.mail-archive.com/podofo-users@lists.sourceforge.net/msg04855.html

**Comment by ceztko** [comment] 2023-01-10 20:58
PoDoFo-next (soon it will be 0.10) is now up and I recommend retry the issue with it for correct working. Please read carefully the [FAQ](https://github.com/podofo/podofo/blob/master/README.md#faq), which are now currently 100% focused on signing.

**Comment by ceztko** [comment] 2023-03-24 22:29
The issue is probably fixed in 0.10.0. If it's not, please re-open.

**Closed by ceztko** 2023-03-24 22:29 UTC
Labels: bug, feedback pending
