### ISSUE TITLE
Mixing Text Object and Q/q is not allowed by spec

### ISSUE THREAD

**Issue by audaki** [podofo/podofo#201] opened 2024-10-21 13:06 UTC
* **I'm submitting a:**
  - [X] Bug report

* **[Bug report] What is the current behavior?**
Text Object and Q/q etc. is mixed

* **[Bug report] What is the expected behavior?**
Text Object is kept separate

* **Please tell us about your environment:**
  - Version/git revision: 0.10.4 and master
  - Operating System: all
  - Package manager used: source

* **[Bug report/Feature request] Other information**
While verifying PDFs generated with Podofo 0.10.4 (and master) I noticed the following warnings:

```
Oct 21, 2024 3:02:34 PM org.verapdf.gf.model.factory.operators.OperatorParser parseOperator
WARNING: Special graphics state operator (q) inside Text object
Oct 21, 2024 3:02:34 PM org.verapdf.gf.model.factory.operators.OperatorParser parseOperator
WARNING: Special graphics state operator (Q) inside Text object
```

After further research, I found out, that this whole mixing should not be allowed:

https://stackoverflow.com/a/65100340

And a good source image (albeit a bit hard to read) linked there:

https://i.sstatic.net/rKvsi.png

**Comment by ceztko** [comment] 2024-10-21 13:59
Does it happen on some "macro" operation? Or it's just allowed?

Maybe removing `StatusTextObject` from these 2 may prevent it happening:

```
void PdfPainter::q_Operator()
{
    checkStream();
    checkStatus(StatusDefault | StatusTextObject);
    PoDoFo::WriteOperator_q(m_stream);
}

void PdfPainter::Q_Operator()
{
    checkStream();
    checkStatus(StatusDefault | StatusTextObject);
    PoDoFo::WriteOperator_Q(m_stream);
}
```

**Comment by audaki** [comment] 2024-10-21 14:12
Sorry for not giving context, it’s the same thing as here: https://github.com/podofo/podofo/issues/197

That means using DrawTextAligned (and very probably other Draw functions) will cause this issue by innately mixing Graphics Operation inside of the Text Block. This was the case before and after the pull-request for Poppler, but I didn’t know yet that it’s against the spec (which would explain why the Poppler library can’t handle this case).

**Comment by ceztko** [comment] 2024-10-21 16:26
Ok, so all the `DrawText` and `DrawTextMultiline` are interleaving graphics and text block operations when doing underline or strike through, which is not allowed, correct? It's possibile this is a regression compared to 0.9.x. Do you plan invest some time in fixing this? From the code it's clear I was trying to factorize single lines text drawing, semantically including underlines/strike through. This may be preserved, but we need to collect the coordinates to be drawn in a list parameter in `drawText` and after draw all the lines separately from the BT/ET enclosing in outer functions, where it makes sense. Would you be able to fix the code like this?

**Comment by audaki** [comment] 2024-10-21 16:29
It probably is a regression to 0.9.8, we are right now in the process of testing a lot of cases after updating our application from 0.9.8 to 0.10; There’s another issue which seems to be a regression from 0.9.8 as well, the color of the text is not applied to the underline. I will have a closer look later and write again to see if this is really a bug and how this is all related to each other.

**Comment by audaki** [comment] 2024-10-22 13:12
After reading the spec https://opensource.adobe.com/dc-acrobat-sdk-docs/pdfstandards/PDF32000_2008.pdf

It seems that starting a text object disallows (among others) "Special Graphics Operators (q, Q, cm)" and "Path Construction (m, l, c, v, y, h, re)" and "Path Painting (S, s, f, F, f*, B, B*, b, b*, n )"

That means that this PDF is probably not valid and that’s then probably why PDF generators usually don’t do this (as a Poppler dev told me) and it’s also why the original version of drawText caused a bug in Poppler, since that library didn’t expect to see this code (albeit most other PDF viewers handled this case differently/better).

I’ve setup a dev environment where I can run podofo 0.9.x and 0.10.x simultaneously, so I will see if I can create a pull-request for this, and potentially find / document more issues

**Comment by audaki** [comment] 2024-10-22 13:13
More info from the spec:

![image](https://github.com/user-attachments/assets/e8ed70f9-f9f3-464f-90fe-baa8e57e1b9d)

**Comment by ceztko** [comment] 2024-10-22 13:31
Thank you for the research. The regression was introduced during a big refactor/cleaning of the painter which costed me a lot in terms of time/efforts. It's possible I suspected mixing of text and graphics operators was not allowed, but Adobe was reacting quite well and also in some cases benefiting by silently allowing it. As said this could be easily fixed by just storing coordinates in  a temporary vector and  drawing them later.

**Comment by audaki** [comment] 2024-10-22 13:43
I will do a pull-request for this later, this is a simple underlined text in podofo 0.9.x

```
q
0.000 0.000 0.000 RG
0.879 w
42.000 418.289 m 62.021 418.289 l S
0.598 w
Q
BT
/Ft6 12.000 Tf
100.000 Tz
0.000 Tc
42.000
420.000
Td <004400440044> Tj
ET
```

and in 0.10.x

```
q
BT
/Ft4 12 Tf
q
0.878906 w
42 418.289062 m
62.021484 418.289062 l
S
0.597656 w
Q
42 420 Td
<020202> Tj
ET
Q
```

**Comment by petervwyatt** [comment] 2024-10-23 04:58
Please PLEASE do not use the PDF 1.7 specification from 2008 (16 years ago!)!

The latest PDF 2.0 specification developed and maintained via vendor-neutral consensus in the ISO forums is available for everyone at [no cost from the PDF Association](https://pdfa.org/sponsored-standards/). This includes a corrected Figure 9 along with 100s of pages of improved descriptions, corrections, clarifications, etc.

**Comment by ceztko** [comment] 2024-10-23 07:49
Thank you for the recommendation Peter! For PoDoFo I already actively use the 2.0 specification. Previously I bought revision ISO32000-2:2017, so I was quite happy ISO 32000-2:2020 became free or charge.

**Comment by audaki** [comment] 2024-10-23 08:29
Hey @petervwyatt 

> Please PLEASE do not use the PDF 1.7 specification from 2008 (16 years ago!)!

We must use PDF/A-3 (and therefore PDF 1.7) for the EU e-invoicing regulations, so this spec is still relevant.

> The latest PDF 2.0 specification developed and maintained via vendor-neutral consensus in the ISO forums is available for everyone at [no cost from the PDF Association](https://pdfa.org/sponsored-standards/). This includes a corrected Figure 9 along with 100s of pages of improved descriptions, corrections, clarifications, etc.

Does it change anything regarding this issue, i.e. is mixing these operators allowed now?

rgds, Kira

**Comment by audaki** [comment] 2024-10-23 08:30
On the topic of this issue again,

@ceztko

There’s a pull-request intended for discussion where I’d need your input on the approach: https://github.com/podofo/podofo/pull/204

**Closed** 2024-10-23 13:57 UTC
Labels: bug

**Comment by ceztko** [comment] 2024-10-23 14:01
I just added https://github.com/podofo/podofo/commit/e41cef19a5302afd61632b4bae217312ad94c4f5 , which is better following the approach I really want to push into fixing the issue. Can you provide more feedback based on this? Anything I am missing?

**Comment by audaki** [comment] 2024-10-23 14:20
I like the approach to have a "work package" (lines to draw) that is then worked on later, seems like a good solution! This is definitely cleaner than my solution would’ve been for draw multiline text

**Comment by petervwyatt** [comment] 2024-10-24 01:26
@audaki—yes, both Table 51 and Figure 9 were corrected in ISO 32000-2 to reflect the long-term reality of PDF files.

And even though PDF/A-3 normatively references ISO 32000-1:2008, that definition of PDF 1.7 is, in many places, inadequate to garner a full and correct understanding sufficient for all implementations. Many legacy sections were rewritten or updated in ISO 32000-2 to ensure (as much as humanly possible) a complete, vendor-neutral, unambiguous, and fully documented understanding of what PDF is - thus referring to ISO 32000-2 whenever there is the slightest ambiguity or lack of clarity in ISO 32000-1:2008 can help to ensure that a correct understanding is always used.

**Comment by ceztko** [comment] 2024-10-24 10:19
Thank you Peter. Looking at the new Figure9 below it looks like "General graphics state" operators (which include `q` and `Q`), are now allowed inside text objects, which using a PDF 2.0 compliant viewer it would in part address the title of this issue. But PoDoFo 0.10.x (regressing from 0.9.x) was doing even more than that as in fact it was doing path construction inside text objects, which it still looks like it's not going to be supported by the spec (but Adobe viewers still handle the scenario quite well). I've fixed that, together stopping using q/Q in text objects because within the context of the PoDoFo functions we're talking about it was not bringing that much benefit anyway.

![image](https://github.com/user-attachments/assets/7fd64615-294b-4f49-a774-bb0ae036e6e9)

**Comment by audaki** [comment] 2024-10-24 10:23
Hey @ceztko, the General Graphics State operators were already allowed in 1.7, so no change there. What changed is that they moved q Q from Special Graphics State to General Graphics State.

![image](https://github.com/user-attachments/assets/3982b660-e51a-4b67-8087-47e5bf9dce0e)

(While the real issue probably where the path construction operators all along anyway, like you also mentioned)
